# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages
env:
  MY_SECRET   : ${{secrets.ACCOUNT}}
  USER_NAME   : garyTsai
  USER_EMAIL  : githubaction@fake.com
  PUBLISH_DIR : ./build
  REACT_APP_APP_KEY : ${{secrets.REACT_APP_APP_KEY}}
  REACT_APP_AUTHDOMAIN : ${{secrets.REACT_APP_AUTHDOMAIN}}
  REACT_APP_DATABSEURL : ${{secrets.REACT_APP_DATABSEURL}}
  REACT_APP_PROJECTID : ${{secrets.REACT_APP_PROJECTID}}
  REACT_APP_STORAGEBUCKET : ${{secrets.REACT_APP_STORAGEBUCKET}}
  REACT_APP_MESSAGEINGSENDERID : ${{secrets.REACT_APP_MESSAGEINGSENDERID}}
  REACT_APP_APPID : ${{secrets.REACT_APP_APPID}}
  REACT_APP_MEASUREMENTID : ${{secrets.REACT_APP_MEASUREMENTID}}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
          - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-to-github-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Install Node JS environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Dependencies
        run: |
          npm install

      # Use Install Dependencies    
      - name: Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm run build

      # Ignore the set-env
      - name: Set Actions Allow Unsecure Commands
        run: |
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV          
      # Use thie action to deploy
      - name: Commit garytsai to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
